### ISSUE TITLE
Bunny::TCPConnectionFailedForAllHosts: Could not establish TCP connection to any of the configured hosts

### ISSUE THREAD

**Issue by ianeinser** [openware/barong#1011]
I got this when i fresh install opendax but compile the image by myself but barong image from you 2.3.45 works fine...

I, [2020-02-01T13:35:58.740472 #1]  INFO -- db:seed: Seeding users
I, [2020-02-01T13:35:58.757016 #1]  INFO -- db:seed: ---
W, [2020-02-01T13:35:59.323383 #1]  WARN -- #<Bunny::Session:0x55e7a8e60a60 guest@localhost:5672, vhost=/, addresses=[localhost:5672]>: Could not establish TCP connection to localhost:5672: Cannot assign requested address - connect(2) for [::1]:5672
{"level":"ANY","time":"2020-02-01 13:35:59 +0000","message":"#<Bunny::TCPConnectionFailedForAllHosts: Could not establish TCP connection to any of the configured hosts>"}

**Comment by ec** [comment]
seems you have defaults in envs connected to rabbitmq.
Check out configuration namings and guidelines
https://github.com/openware/barong/blob/master/docs/configuration.md#dependencies-configuration-vault-redis-rabbitmq
