### ISSUE TITLE
I can verify my phone with ANY random number

### ISSUE THREAD

**Issue by sundanny26** [openware/barong#1018]
v: barong 2.3.45
When I add a phone number I can enter ANY random code and the phone verifies

**Comment by ec** [comment]
@sundanny26  That is expected if you have "mock" policy for phone verification, which acts exactly as you have described)
check if you have configured BARONG_PHONE_VERIFICATION env

Please check corresponding documentation
https://github.com/openware/barong/blob/2-3-stable/docs/configuration.md#twilio-configuration

**Comment by sundanny26** [comment]
Worked like a charm. Thnks mate
