### ISSUE TITLE
[login] can users be blocked after several attempts

### ISSUE THREAD

**Issue by sundanny26** [openware/barong#1025]
When I fail at logging in several time user never gets block. is there any way to activate this?

**Comment by ec** [comment]
@sundanny26 no, in current version this feature is not available. It was in 1.8, but we decided to remove gem `devise` which was responsible for this functionality, as it is too huge and slow.

**Comment by bitcoinsfacil** [comment]
@ec what is the recommended path to avoid brute forcing the account if `google captcha` is not an option?

**Comment by ec** [comment]
@bitcoinsfacil what about geetest captcha?
We support 2 captcha. Geetest and Google Recaptcha

**Comment by rubi022** [comment]
@ec 
captcha. Geetest and Google Recaptcha etc protects from spam 
but there are many services like anti-captcha[.]com they brute force email password for account.
