### ISSUE TITLE
500 Internal server error when login

### ISSUE THREAD

**Issue by kroim** [openware/barong#1034]
Request URL: http://www.app.local/api/v2/barong/identity/sessions
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 0.0.0.0:80
![image](https://user-images.githubusercontent.com/33049672/77024615-ec2df800-69c9-11ea-8ffb-0c3cdd55fbb3.png)

**Comment by ec** [comment]
While sending this kind of errors, please, include the logs of the server

**Comment by ec** [comment]
closed due to inactivity
