### ISSUE TITLE
Auto Logout after login within 1 seconds

### ISSUE THREAD

**Issue by kroim** [openware/barong#1043]
If I check the barong session, it is expired soon and it is working with other session key. 
So, I think that it is logging out automatically soon.
Why?

**Comment by kroim** [comment]
Cookie: _barong_session=eb49800bf3390a00e339a95765a8f369
This _barong_session is changed.
So, I think that logged out automatically.
Please help me for this.

**Comment by ec** [comment]
Session changes after 401 - session denied, which invalidates your session.
Im pretty sure you are missing BARONG_REDIS_URL env

**Comment by kroim** [comment]
I think that I set it correctly.
![image](https://user-images.githubusercontent.com/33049672/77627174-71447e80-6f81-11ea-9274-65e37a19364e.png)

**Comment by ec** [comment]
@kroim please specify the version of barong and infrastructure you use. its an opendax?

**Comment by kroim** [comment]
Yes, it is an opendax and I used latest versions.

**Comment by ec** [comment]
@kroim I see. For now, please, downgrade Barong version, as it's not compatible with latest opendax. There is an issue on opendax side (in traefik version). You can try to update traefik version by yourself or wait for Openware update and downgrade, meanwhile, Barong version

**Comment by kroim** [comment]
I see. I will should use latest version. If not, other config will be broken.
I will continue to resolve it continue myself.

**Comment by ec** [comment]
closed due to inactivity.
Feel free to reopen if issue still actual for you

**Comment by kroim** [comment]
I didn't solve this problem in new version yet. 
New version means more than 2.4.x

**Comment by ec** [comment]
@kroim i meant an opendax version more that a barong one, as soon as its a proxy problem, and not a barong.

**Comment by kroim** [comment]
proxy?

**Comment by ec** [comment]
@kroim traefik

**Comment by ec** [comment]
> There is an issue on opendax side (in traefik version).

@kroim i have pointed it earlier

**Comment by kroim** [comment]
Yes, I saw, but I didn't find the issue, Please let me try continue. Or please help me if possible.

**Comment by ec** [comment]
@kroim upgrade traefik version like this https://github.com/openware/opendax/commit/c4253eb62be53efda47184bce0832834245da65a

**Comment by ec** [comment]
@kroim https://github.com/openware/opendax/commit/b6beef4398daf601dddc9457f8a4e5d0a76faf30

try to use opendax master

**Comment by kroim** [comment]
Yes, I am using the master branch in opendax.
