### ISSUE TITLE
jwt.decode_and_verify

### ISSUE THREAD

**Issue by ImanMousavi** [openware/barong#1070]
hi, I get jwt.decode_and_verify in developmet mode

![Screenshot from 2020-05-14 01-08-51](https://user-images.githubusercontent.com/11661963/81862857-987dfc00-957f-11ea-94e2-37b2241a7a30.png)

![image](https://user-images.githubusercontent.com/11661963/81893894-dd2b8680-95c3-11ea-8d29-9b8750d8f4c3.png)

![image](https://user-images.githubusercontent.com/11661963/81893931-ecaacf80-95c3-11ea-8116-1e59f98c8ba7.png)

**Comment by ec** [comment]
Hello @irmaster ! Sorry for delay in response, was a bit busy lately.

You should get JWT from /auth endpoint first. Seems you use barong as standalone. Its much more convenient to use it with ambassador or envoy, so it will do the job of getting JWT for you

**Comment by ImanMousavi** [comment]
thank you so much

**Comment by charyc** [comment]
guys can you help me as well . . hitting /auth gives me 'ok' but not jwt token

**Comment by ImanMousavi** [comment]
Start rails server JWT_PUBLIC_KEY=\$(cat config/secrets/rsa-key.pub| base64 -w0) rails s -b 0.0.0.0 (base64 -b0 for macOS)
