### ISSUE TITLE
Barong 2.5.4 maililng issue

### ISSUE THREAD

**Issue by harold-whistler** [openware/barong#1107]
Hello there,
opendax 2.5 with barong 2.5.4, baseapp 2.5.0 and tower 2.5.0
As a mail sending agent using Sendgrid. Credentials are checked and works just fine. 

When user register, Barong doesn't sending any mails, same story with new session and other kind emails. Its clean installation. 
Mail container logs contain only:
```
docker logs d1d714892ad4
[DEPRECATION] Passing a options hash and a block to `desc` is deprecated. Move all hash options to block.
[DEPRECATION] Passing a options hash and a block to `desc` is deprecated. Move all hash options to block.
[DEPRECATION] Passing a options hash and a block to `desc` is deprecated. Move all hash options to block.
[DEPRECATION] Passing a options hash and a block to `desc` is deprecated. Move all hash options to block.
```

No errors or anything else, SendGrid doesn't see anything in logs - no attempts to send anything.

**Comment by phuongdev89** [comment]
same problem, but when I deploy on local, it's running

**Comment by ec** [comment]
Hi! There is clearly logs problem, to see the logs try to run mailer from inside the container `./bin/mailer run` from bash.

You will see the logs, and they will tell you what is the problem. Usually its a configuration or template problem.
Ill close this, as we have multiple confirmations it works correctly if your configs are OK. So pls, open the corresponding issue at opendax, if you use it.

**Comment by harold-whistler** [comment]
> ./bin/mailer run

getting this in logs:
`{"level":"ERROR","time":"2020-07-26 02:08:15 +0000","message":"#<ActionView::Template::Error: undefined method `url' for nil:NilClass>"}`

**Comment by sundanny26** [comment]
Was this resolved @ec  ?
