### ISSUE TITLE
Undefined Variable permission in seed_restrictions

### ISSUE THREAD

**Issue by martianatwork** [openware/barong#1110]
https://github.com/openware/barong/blob/2c259c47ada96c43fafa5f679f0bb71670ea319f/lib/barong/seed.rb#L116

**Comment by ec** [comment]
Thanks for the tip!) Yes, we know about that, i will prepare fix today

**Comment by martianatwork** [comment]
@ec while you are on it, there is an issue with restrictions seeds as well, we should check if the record exists before creating restrictions

**Comment by ec** [comment]
@martianatwork yes, i meant this one as well) It appeared because of changing restrictions uniqueness policy without proper updating of seeds.

**Comment by chumaknadya** [comment]
Fixed on 2-6-stable, 2-5-stable, master
