### ISSUE TITLE
How to change admin user?

### ISSUE THREAD

**Issue by pooyagolchian** [openware/barong#1122]
I change the user configuration template in seed.yml.rb 
users:
  - email: admin@barong.io
    password: 0lDHd9ufs9t@
    role: admin
    state: active
    level: 3
  - email: john@barong.io
    password: Am8icnzEI3d!
    role: member
    state: active
    level: 3

but have an error in the build: Can't create user 'john@example.com': Password requirements
How to add an admin users in this system?

**Comment by ec** [comment]
Try to change a password or just add an admin from the rails console inside container)

**Comment by pooyagolchian** [comment]
@ec  Give me an example, Please. The documents not complete for change admin users or add wallet types like warm, hot, or cold wallet addresses.

**Comment by coincryptoexchange** [comment]
In the seed file like mentioned above i add my superadmin user. When i do rake service:all 
It is not loading this seed file. it just resets it to the above one. How can I add Superadmin user?

**Comment by chumaknadya** [comment]
@coincryptoexchange 
Every time when you run command rake service:all, you have db:seed rake task in it
To seeds new file you need to be sure that you don't have old values in DB, you can delete them and then execute rake service:all again, and it should be okay

**Comment by chumaknadya** [comment]
Closed due to inactivity
If you still have question please open issue on opendax repo
