### ISSUE TITLE
wrong customer id or password,please try again

### ISSUE THREAD

**Issue by ksystemsio** [openware/barong#631]
Hello everyone, I run workbench on custom domain, but I get this error immediately after clicking on "Sign in with Barong" on api.mydomain. 

Any idea why this would happen? I read in issue #509 that this could be a problem with nginx and passenger, but I cannot see any info on how to fix it. 

I am not running 2FA at the moment

**Comment by ec** [comment]
Mainly, this error might come because of the wrong configurations.
Steps to fix: (probably)
1. Check application.yml
```
  BARONG_CLIENT_ID:           ~
  BARONG_CLIENT_SECRET:       ~
  BARONG_DOMAIN:              ~
  BARONG_OAUTH2_REDIRECT_URL: ~ # Specify URL address to which user will be redirected after successful sign in.
```
2. Try to erase the database. Sometimes it register wrong authentication, if first configs wasn't right

**Comment by ec** [comment]
Try to follow public videos how to setup workbench properly
After fixing some configs it will work for you
