### ISSUE TITLE
[Feature Request] Add the ability to search user by email on barong admin page

### ISSUE THREAD

**Issue by lizhuomeng71** [openware/barong#635]
User Story:

As a customer support, I often need to find user's account in barong admin page to help them resolve issues, such as enable/disable their 2fa.

Currently, I need to go from page to page to find user's email, this is not feasible once the user base is over 1000 users.

I would like to request an search function on barong / Accounts pages
![tempsnip](https://user-images.githubusercontent.com/7528736/47152214-e68e2900-d290-11e8-99ec-eea90240eca8.png)

**Comment by ec** [comment]
Currently, v2 supports pagination and strict search aka by lvl / role / email
