### ISSUE TITLE
[Bug] Devise:Lockable:time Not working for User/api/V1

### ISSUE THREAD

**Issue by lizhuomeng71** [openware/barong#636]
Step to Reproduce:

1. Through API, Login with wrong password for more than 5 times.
2. Account is locked
3. Wait for more than 1 hour, (Or Change the database Account->locked_at to more than 1 hours ago
4. Sent an Request to /api/v1/accounts/send_unlock_instructions

Expect:
An Unlock instruction email should be sent

Actual:
Error Message "Your Account is not locked"
While the account is in fact locked

Note:
I understand this bug may relate to auto unlock after 1 hour, but seems it's not auto locking, and it prevent me to sent an unlock email after 1 hour

This is a blocker bug, because once user get into that states, there is no way to unlock the account (by user. by admin or by anybody except to update the database)

Release Version
1.8.35

**Comment by lizhuomeng71** [comment]
Update: unlock flow works fine is log in via barong user interface/
However
Under app/api/user_api/v1/session.rb
line 53
          error!('Your account was locked!', 401) unless account.locked_at.nil?

only check if locked_at is nil, time lock is not checked,

**Comment by ec** [comment]
Hello! We confirm issue exists. Please 
You can open a PR regarding the issue or wait for fix!
Thanks a lot, will keep you up to date

**Comment by laertispappas** [comment]
Is this a bug or a feature? It looks like a [feature](https://github.com/rubykube/barong/blob/master/config/initializers/devise.rb#L198) to me.

**Comment by laertispappas** [comment]
Is this a bug or a feature?
https://github.com/rubykube/barong/blob/master/config/initializers/devise.rb#L198

**Comment by m-an** [comment]
Fixed in 1.9 by https://github.com/rubykube/barong/pull/649

**Comment by ec** [comment]
Approved fix by #649
