### ISSUE TITLE
[Barong v2] Api_Keys endpoint response with `500 internal server error`

### ISSUE THREAD

**Issue by pkucherenk0** [openware/barong#662]
When the 2FA code was not enabled for account the response was as expected: `Only accounts with enabled 2FA alowed`, but when it was enabled, the new cookie with otp_code `/api/v2/barong/identity/sessions`  was created, response was `"error": "Something went wrong"` .

Logs of Barong:

![selection_759](https://user-images.githubusercontent.com/38254545/49227199-3401c800-f3f1-11e8-980a-68b5b5158cba.png)

**Comment by alinetskyi** [comment]
I can't reproduce the issue, what do you mean by a new cookie with otp_code was created?
When I try to access api_keys without 2fa I get the expected error

**Comment by pkucherenk0** [comment]
@alinetskyi When account dose not have 2FA the error is correct, its when 2FA enabled i can get the api key. 
By `a new cookie with otp_code was created` i mean that i have to create a new session so it contain information about 2FA been enabled. (I thought it might help but it didn't)

Steps to reproduce:
1. Log in as account without 2FA
2. Generate QR code to enable 2FA with `Post  /api/v2/barong/resource/otp/generate_qrcode`
3. Enable 2FA with `Post  /api/v2/barong/resource/otp/enable`
4. Try to get an api key with `Get  /api/v2/barong/resource/api_keys`

Result: 
![selection_762](https://user-images.githubusercontent.com/38254545/49278793-79280780-f48e-11e8-827f-cfafa5514d65.png)

**Comment by ec** [comment]
#675 follow the PR
