### ISSUE TITLE
[Barong v2; Feature request] handle document expired date.

### ISSUE THREAD

**Issue by pkucherenk0** [openware/barong#666]
When user proceed in KYC process he needs to upload document to reach (by default) max level required to do a withdraw.
Document upload have few validations to prevent too large images and document expire date.
Document expire date validation point is to prevent uploading if document is already expired, after document was uploaded it becomes totally manual process.

I suggest that Barong compare the date of expire with the current date and in case of match decrease user level by changing label to `document:expire`.
It also will be useful to send a warning email to a user.

**Comment by arruah** [comment]
@GitCash send .00000001 bch to @pkucherenk0

**Comment by alwaysAn0n** [comment]
@GitCash send 1 usd to @pkucherenk0

@arruah That's too little!

:)

**Comment by GitCash** [comment]
Hey **pkucherenk0**, user **alwaysAn0n** tipped you **10638 bits** in Bitcoin Cash ( ~ **$1** ).

*[Click here to claim it!](https://gitcash.io/claim/pkucherenk0)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.

**Comment by arruah** [comment]
@alwaysAn0n Just testing :) What is minimal amount to tip?

**Comment by alwaysAn0n** [comment]
@arruah There is no explicit minimum but in practice the tip will probably be rejected by the network if it's for an amount less than the (dust threshhold)[https://www.reddit.com/r/btc/comments/7qc3lh/initiative_to_get_rid_of_dust_threshold]

Sorry for dirtying up your issue with our conversation .  Also, what a lucky issue number!

@GitCash send @pkucherenk0 and @ec 2 bucks more

**Comment by GitCash** [comment]
Hey **pkucherenk0,@ec**, user **alwaysAn0n** tipped you **21276 bits** in Bitcoin Cash ( ~ **$2** ).

*[Click here to claim it!](https://gitcash.io/)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.

**Comment by GitCash** [comment]
Hey **pkucherenk0,@ec**, user **alwaysAn0n** tipped you **21276 bits** in Bitcoin Cash ( ~ **$2** ).

*[Click here to claim it!](https://gitcash.io/)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.

**Comment by ec** [comment]
frozen
