### ISSUE TITLE
RuntimeError: No EVENT_API_JWT_PRIVATE_KEY found in env!

### ISSUE THREAD

**Issue by parnaa** [openware/barong#692]
Using workbench  I tried  to install  Peatio  and while running
`docker-compose run --rm barong bash -c "./bin/link_config && ./bin/setup"`

I got the following  error

`D, [2018-12-17T16:59:04.371523 #15] DEBUG -- :   ↳ lib/barong/seed.rb:62
D, [2018-12-17T16:59:04.447328 #15] DEBUG -- :    (74.0ms)  COMMIT
D, [2018-12-17T16:59:04.447822 #15] DEBUG -- :   ↳ lib/barong/seed.rb:62
A, [2018-12-17T16:59:04.449991 #15]   ANY -- : #<RuntimeError: No EVENT_API_JWT_PRIVATE_KEY found in env!>
A, [2018-12-17T16:59:04.450782 #15]   ANY -- : /home/app/lib/barong/event_api.rb:147:in `rescue in call'
`

**Comment by ec** [comment]
If you run barong in development mode - set the env `EVENT_API_JWT_PRIVATE_KEY`
Or paste the env in the development.rb
