### ISSUE TITLE
Password Reset Token doesn't expire

### ISSUE THREAD

**Issue by martianatwork** [openware/barong#727]

**Comment by ec** [comment]
Hello @martianatwork . In previous versions token expire was handled by devise, and as soon as we have dropped the dependency we need to blacklist it in our own.

This is a known issue and fixing it already in the roadmap.

**Comment by ec** [comment]
Hello @martianatwork 
https://github.com/rubykube/barong/pull/734
this is the first step in fixing the bug
We will store used tokens in redis cache soon
