### ISSUE TITLE
Rework errors to be strict to one standard

### ISSUE THREAD

**Issue by ec** [openware/barong#728]
Should be
```
[
    { code: 2001, message: 'error text' },
    { code: 2001, message: 'error text' }
]
```

**Comment by mod** [comment]
we need to make an error index, and display { code: XXXX, message: "Default message" }
it will help translating errors.
the error index will be also commited in javascript somehow

**Comment by ec** [comment]
Done by :
#774 
#741 
(some errors also fixed/added with small patches)
All the list can be founded here https://github.com/rubykube/barong/blob/master/docs/errors.md
