### ISSUE TITLE
Configuration mail

### ISSUE THREAD

**Issue by kiirkrein** [openware/barong#729]
Hello,

I search a configuration file for sending confirmation mail.

In barong.env i replace a SMTP_ADDRESS per "my domain" port 587 but its dont working but its working with mailcatcher when i replace the SMTP_ADRESS per "mailcatcher" port 1025.

(I can send mail from my server, its work.)

Thx for uur help.

**Comment by ec** [comment]
Please specify the version you use

**Comment by kiirkrein** [comment]
Hello ec and thx for reply.

I using 1.8.5 version.

**Comment by andyduong1920** [comment]
@ec For me, I have a problem with the confirmation email, I saw in the **confirmation_controllers** we will redirect the user to a domain base on the **redirect_uri** param, my question is, where is the **redirect_uri** param come from, I can't see it on the confirmation instructions email 🤔

**Comment by ec** [comment]
In 1.8 and 1.9 versions all the sensitive data specifies by ENVs.
Your problem was, that `SMTP_ADDRESS` is not your domain, but address provided by SMTP to enable sending emails (3d party app).
`Redirect_uri specifies by env.`
