### ISSUE TITLE
Routing error

### ISSUE THREAD

**Issue by rastislavcore** [openware/barong#752]
Login from Peatio give me error:
```
No route matches [GET] "/oauth/authorize"
Rails.root: /Users/banana/code/barong

Application Trace | Framework Trace | Full Trace
actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.2) lib/rails/rack/logger.rb:28:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.2.2) lib/rails/engine.rb:524:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

Not sure what cause problem. Seems like bug.
Please, discuss.

**Comment by ec** [comment]
While opening the issues, please, specify the version you use @raisty

**Comment by selvaraman** [comment]
I am facing the same problem. I cloned [barong](https://github.com/rubykube/barong.git) and it's [test client](https://github.com/rubykube/barong-client-app). When I click **Authorize via Barong** link in test client app, I got the following error in barong log.
`I, [2019-02-14T12:45:17.197422 #24990]  INFO -- : Started GET "/oauth/authorize?client_id=0121361bd7288f9228e401aa79a36cfbc44e68047c3c6c822aa7cb1feedcd20a&redirect_uri=http%3A%2F%2Flocalhost%3A3001%2Foauth%2Fcallback&response_type=code" for 127.0.0.1 at 2019-02-14 12:45:17 +0530
F, [2019-02-14T12:45:17.199606 #24990] FATAL -- :   
F, [2019-02-14T12:45:17.199700 #24990] FATAL -- : ActionController::RoutingError (No route matches [GET] "/oauth/authorize"):
F, [2019-02-14T12:45:17.199733 #24990] FATAL -- :   
F, [2019-02-14T12:45:17.200919 #24990] FATAL -- : actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
`
How to resolve this?

**Comment by ec** [comment]
barong-client-app is a bit outdated one.
I guess all the problems comes just from using it.
Try to use workbench for 1.8 and 1.9 versions and microkube for 2.X versions
