### ISSUE TITLE
How to use file Local file storage in production env?

### ISSUE THREAD

**Issue by martianatwork** [openware/barong#764]
is it possible to use local storage in production env?

**Comment by ec** [comment]
@martianatwork Its highly NOT recommended.
Production env shouldn't use local file storage

**Comment by martianatwork** [comment]
@ec Yes i know that but i'm using microkube which uses production env by default so thats why i asked.

**Comment by ec** [comment]
TO confirm:
Using local file storage in production env is not allowed, configure bucket.
