### ISSUE TITLE
authz unexpected behaivor with incorrect api_key

### ISSUE THREAD

**Issue by m-an** [openware/barong#770]
When I set wrong api_key headers, I receive 404 status with html error in body instead of json on api call,
while when I set an empty headers, I get json error with 422 status.
Proofs attached
![deepinscreenshot_select-area_20190218113626](https://user-images.githubusercontent.com/15743844/52942662-0edb8080-3374-11e9-8ddd-8700e870f6ef.png)
![deepinscreenshot_select-area_20190218113728](https://user-images.githubusercontent.com/15743844/52942669-13079e00-3374-11e9-8010-63516d9bbd6d.png)

**Comment by ec** [comment]
confirmed

**Comment by ec** [comment]
@m-an #768 PR with fix ready.
Will be merged soon in master
