### ISSUE TITLE
Implement api keys scope logic

### ISSUE THREAD

**Issue by ec** [openware/barong#779]

**Comment by ec** [comment]
frozen

**Comment by jloup** [comment]
Hi, 

I was used to old version of Barong (pre 2.0.0) and I am currently looking into the last version.

I appreciate most of the improvements but two points:
- permissions system is hairy
- still a lack of API keys scope handing

Permissions system is too complicated (request verb + path + action) and does not work across applications (applogic, peatio).
API key scopes is a must have.

I have a suggestion. Why not just associate a role with scopes ? It would make everything simpler and working across applications.
A role would be given a subset of all scopes possible. When an API key is created, we let user choose which scopes it has access to be forwarded to API key.
Example: role `member` is given scopes: `read_orders`, `write_orders`, `read_withdraws`, `write_withdraws`. An API key for this role can be created with just this subset of scopes: `read_orders`, `read_withdraws`.

With scopes encoded in JWT, we could simply check in any project if current JWT can access an endpoint by checking endpoint required scope (+ multi signature for management APIs which works very well).

What do you think ? Am I missing something ?
