### ISSUE TITLE
withCredentials error 

### ISSUE THREAD

**Issue by huuhait** [openware/barong#788]
withCredentials: false work => can't set cookie
withCredentials: true not work 😐
![image](https://user-images.githubusercontent.com/40519768/53557326-40c0c400-3b78-11e9-9d07-b048dbf44c96.png)

**Comment by mnaichuk** [comment]
Hi @Thedabest!
Access-Control-Allow-Credentials response header is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’. Try to set list of allowed origins.

**Comment by huuhait** [comment]
tks @mnaichuk

**Comment by huuhait** [comment]
Closed

**Comment by gelinger777** [comment]
@mnaichuk  but what to do with the cookie? Let's say I want to  develop a UI on  local machine, where i have Nuxt script running on localhost:3000 , but Barong's API Sets the cookie on  app.blabla.com domain, which is not only httpOnly but also hostOnly. 
Any way to  overcome this for development purposes?
