### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by endofthepain** [openware/barong#796]
Hello, i have little a problem on production mode

when user register, barong said "rollback" mean this account not submitted on mysql database
 
<img width="924" alt="screen shot 2019-03-05 at 12 16 03" src="https://user-images.githubusercontent.com/11496089/53783426-1d18c780-3f44-11e9-8661-d3c034c9afd4.png">

this have been fixed after i am restart barong container 2 times, but my question its a normal ? or something i miss

**Comment by ec** [comment]
As log says, user with such email already recorded in database :)

`User Exists` - means this email already taken.
Your front end or api call response should contain an error, so be more attentive.

I'll close this. Just be sure you haven't registering accounts on same email (which is `cryptoiz.suport@gmail.com` due to log)

**Comment by endofthepain** [comment]
sorry i am open again, cause this problem still same
<img width="1159" alt="screen shot 2019-03-05 at 17 00 55" src="https://user-images.githubusercontent.com/11496089/53797477-d7222a80-3f68-11e9-946b-d9ce3020acbb.png">
<img width="1538" alt="screen shot 2019-03-05 at 17 01 14" src="https://user-images.githubusercontent.com/11496089/53797478-d7bac100-3f68-11e9-8b47-18859588f313.png">

logs said the member was exist but on database the UID or email its not found

**Comment by ec** [comment]
@endofthepain can't reproduce this. How can we sync on the topic?
For me it works pretty well

**Comment by ghost** [comment]
when you run bundle exec rake db:create db:migrate did you get any error like  
FATAL -- : Private key is invalid
rake aborted!
am having such error how do i solve it.

**Comment by endofthepain** [comment]
@ec i was found my problem, this problem is from password validation and now i was fixed thanks for your respons i close it @laugh26 u can see mikrokube example for your question
