### ISSUE TITLE
Private key is invalid 

### ISSUE THREAD

**Issue by ghost** [openware/barong#798]
When i run bin/rails credentials:edit i get this error
F, [2019-03-05T20:46:11.078443 #57557] FATAL -- : Private key is invalid

**Comment by ghost** [comment]
solved

**Comment by mudspot** [comment]
@laugh26 hi! how did you solve this?

**Comment by tonoezep** [comment]
@laugh26 please, can you tell me how you solved this?

**Comment by btczo** [comment]
@tonoezep have you solved it?

**Comment by pblab-dev** [comment]
how to solve it?
