### ISSUE TITLE
How to generate OTP using barong?

### ISSUE THREAD

**Issue by StDogbert** [openware/barong#817]
Stuck trying to generate OTP using barong. Can't find related documentation and all the steps required. Any directions?

**Comment by ec** [comment]
Hello @StDogbert 
Barong have an API to create a QR code, compatible with your google authenticator
Here is related code https://github.com/rubykube/barong/blob/master/app/api/v2/resource/otp.rb#L15

And related api doc 
https://github.com/rubykube/barong/blob/master/docs/rest_api.md#resourceotpgenerate_qrcode

Remember, for this feature you should have running vault

**Comment by StDogbert** [comment]
Many thanks! Managed to do it and perform a withdrawal.
