### ISSUE TITLE
BUG: Barong and Postmaster do not communicate well

### ISSUE THREAD

**Issue by ianeinser** [openware/barong#818]
Hi @mod @ec  ,

i just download the latest master branch of barong.. then i tried to do sign up with postmaster.. the postmaster fails because it needs barong to send event message with language field set.. the language field is optional but it is empty, postmaster will not process the event (email confirmation) correctly.

https://github.com/rubykube/barong/blob/master/app/api/v2/identity/users.rb

the lang param should be set and it seems it is not an optional field anymore

**Comment by ec** [comment]
Hi @ianeinser , you totally right!
I just checked, i missed very important thing.

In all other endpoints if optional param `lang` is not put in - barong sends 'EN' by default.
But this is missing on automatic event on user creation.

Wait few minutes, i will push a fix

**Comment by ec** [comment]
@ianeinser please follow https://github.com/rubykube/barong/pull/820
I will add some specs and we merge soon

**Comment by ec** [comment]
@ianeinser 2.2.10 #820 merged
