### ISSUE TITLE
Barong api session create don't return tokens

### ISSUE THREAD

**Issue by top1st** [openware/barong#832]
![image](https://user-images.githubusercontent.com/23559697/58012295-c1171580-7b26-11e9-8434-ad606a85f111.png)

Current master branch api session create return like this?
What i am wrong?

**Comment by pkucherenk0** [comment]
Check Headers
![Selection_302](https://user-images.githubusercontent.com/38254545/58012582-79c85f00-7afd-11e9-9032-f45b6f9052c5.png)

**Comment by ec** [comment]
You are not wrong )
Current master branch version is 2.1
In v2 user doesnt interact with JWT tokens, only with session cookies.

With this request you have received cookies. Now you are ready to go. Gateway can send your request through Barong AuthZ endpoint and inject a JWT in your request.
Try microkube to get started.

If you want to have JWT in some reasons, try to send any type of request (GET, POST, etc)
to `/api/v2/auth/anyrandompath`

It should return you  JWT token

**Comment by top1st** [comment]
thank you. I have set the cookies in postgress config. after that make request to resource/users/me

i am getting errors

![image](https://user-images.githubusercontent.com/23559697/58028340-1bc36800-7b4d-11e9-82b9-3747360c1c05.png)

Can i get v2 api documentation follow?

**Comment by top1st** [comment]
Okay thank you. session was expired

**Comment by top1st** [comment]
I can get the jwt token for barong with /api/v2/auth/anyrandompath.
With the Cookie from barong/identity/sessions
![image](https://user-images.githubusercontent.com/23559697/58164015-9c05dc80-7cb7-11e9-80e9-3e2d6efe5845.png)

I can use this cookie for peatio api access?
I have checked the default microapp but it not works with current master branch peatio & barong.
Can I get instruction about api app flow logic?

**Comment by ec** [comment]
Yes.
Take a look
![image](https://user-images.githubusercontent.com/25320212/58164342-52ed6280-7c8e-11e9-8802-8c81bc2e83a7.png)

> User sends cookies to gateway
> Gateway sends cookies to AuthZ
> AuthZ return to gateway JWT
> Gateway inject JWT into request and sends to API (peatio, barong, applogic, etc)

Try microkube to get started

**Comment by top1st** [comment]
> Gateway inject JWT

Api GateWay Logic is very good.

Can I check the gateway code? what is the github repo for Gateway? Not just docker image

**Comment by kroim** [comment]
I am getting error (Route isnot found 404) in app.local page.
![image](https://user-images.githubusercontent.com/33049672/76969418-4f397380-6965-11ea-9928-03796f6d4967.png)
What is reason?
