### ISSUE TITLE
ActionController::InvalidAuthenticityToken in SessionsController#confirm

### ISSUE THREAD

**Issue by AnythingLinux** [openware/barong#866]
I am using Debian 9 Linux when i click on Submit Button Signin form it show

ActionController::InvalidAuthenticityToken in SessionsController#confirm
ActionController::InvalidAuthenticityToken

![Screenshot from 2019-07-07 04-31-56](https://user-images.githubusercontent.com/1058663/60761731-335c9e80-a070-11e9-88b7-b54b8f6fc1db.png)
![Screenshot from 2019-07-07 04-32-07](https://user-images.githubusercontent.com/1058663/60761732-335c9e80-a070-11e9-947c-d0af8a788348.png)

**Comment by ec** [comment]
Cant provide hint due to the lack of the details.
But, i will highly recommend to try microkube for v2 and workbench for 1.9

It goes with instructions and great get started:
https://github.com/rubykube/microkube v2
https://github.com/rubykube/workbench

**Comment by AnythingLinux** [comment]
@ec yes i have used microkube for v2 and stuck when i see "Trades coming soon!" 
check this close issue rubykube/microkube#92
it also asking me to installing Peatio 1.9 with the workbench project. I am confuse wheather i will use workbench or microkube ?

**Comment by guru260** [comment]
I am also facing the same issue.
