### ISSUE TITLE
An error occurred while installing mysql2 (0.5.2), and Bundler cannot continue. Make sure that `gem install mysql2 -v '0.5.2' --source 'https://rubygems.org/'` succeeds before bundling.

### ISSUE THREAD

**Issue by AnythingLinux** [openware/barong#873]
i am using baron 1.9. when i run $ bundle install is shows:

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/mysql2-0.5.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/mysql2-0.5.2 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/mysql2-0.5.2/gem_make.out

An error occurred while installing mysql2 (0.5.2), and Bundler cannot continue.
Make sure that `gem install mysql2 -v '0.5.2' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  mysql2
![Screenshot from 2019-07-19 03-56-28](https://user-images.githubusercontent.com/1058663/61494929-5b85bf00-a9d9-11e9-9dfe-76fce8ea97c1.png)

Need help

**Comment by tuballeonel** [comment]
sudo apt-get install libmysqlclient-dev

**Comment by Saif-hub24** [comment]
I have same issue, @tuballeonel  your solution not work for me. i am on ubuntu.

**Comment by emads3** [comment]
I have the same issue

**Comment by Usman1436** [comment]
This worked for me......

sudo apt-get -f install
sudo apt-get update
sudo apt-get install libmysqlclient-dev
bundle install
