### ISSUE TITLE
Missing storage_region env config for carrierwave

### ISSUE THREAD

**Issue by martianatwork** [openware/barong#880]
required for AWS

https://github.com/rubykube/barong/blob/ceedc0d3b2c7cf6d05ff5a2ae1c05102adad98d2/config/initializers/carrierwave.rb#L29

**Comment by ec** [comment]
Thank you @martianatwork )
We will submit a pr soon

**Comment by ec** [comment]
Fixed in 2.3.16 with 76e3fc0e93528c5a2c46057272abb11551305d44
