### ISSUE TITLE
Permissions are not checked

### ISSUE THREAD

**Issue by jloup** [openware/barong#889]
I might be missing something big but it seems you check permissions only at `api/v2/auth/path*` endpoint call.

With a `member` user if I call `api/v2/auth/admin`, I got a `authz.invalid_permission` as expected.

But what does refrain me to get a Authorization token by calling `api/v2/auth/api/v2/barong/resource` (which `member` can access)
and then call `api/v2/auth/admin/metrics` for instance ?

I do not see any permissions validation after the auth call.

**Comment by ec** [comment]
Yes, but end user doesn't have a JWT in any case.
If you have it in response in your installation, then you have mistakes in your configurations.

This works because of the "gateway" architecture

**Comment by jloup** [comment]
I missed this, I was taking barong as standalone, thanks
