### ISSUE TITLE
How to configure session expire time?

### ISSUE THREAD

**Issue by StDogbert** [openware/barong#900]
I have troubles trying to configure session expiration time from microkube. I know its possible after https://github.com/rubykube/barong/pull/720, but don't really understand how to set it from env file and if its even possible. Any suggestions?

**Comment by ec** [comment]
@StDogbert hello!
Try to set ENV 
`SESSION_EXPIRE_TIME`

by default its 1800 (sec)

**Comment by StDogbert** [comment]
Thanks! That did it. I am not sure how (cause there is no such variable in barong), did it translated to session_expire_time (lowercased)? Anyway, many thanks!

**Comment by ec** [comment]
@StDogbert yes, it is)
You can see a lot of envs over the project like
Barong::App.config.lowercased_env_name
