### ISSUE TITLE
Unify configs

### ISSUE THREAD

**Issue by mod** [openware/barong#998]
1) Unify all Env with a auto prefix BARONG_

Remove configure that can be avoided
Make sure we validate all values on start up
Search for ENV.fetch left over
Comment in code description of configs.

2) Make an index table on the readme with all config

Table should include default value, valid values
Description of Variable.

3) Configuration endpoint

Make a public configuration endpoint and exposing all non-sensitive params.
Barong Version, Captcha, Session timeout for Auto-logout, suggest all possible values in your patch,

If admin or a user is requesting we could show more config for debug help or admin panel debugging.

**Comment by ec** [comment]
duplicate #997
